query allGames($offset: Int) {
  games(
    gameType: NOUGHTS_AND_CROSSES,
    filters: {
      limit: 24,
      offset: $offset,
    },
  ) {
    ...on NoughtsAndCrossesGame {
      id
      bots { name }
      result {
        victor { name }
      }
      startTime
      contest {
        name
      }
    }
  }
}
