export const SOCKET_OPEN = 'SOCKET_OPEN';
export const SOCKET_CLOSE = 'SOCKET_CLOSE';
export const SOCKET_ERROR = 'SOCKET_ERROR';
export const SOCKET_INCOMING = 'SOCKET_INCOMING';
export const SOCKET_OUTGOING = 'SOCKET_OUTGOING';

export const AUTHENTICATE_ADD = 'AUTHENTICATE_ADD';
export const AUTHENTICATE_REMOVE = 'AUTHENTICATE_REMOVE';
